backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "media"

public_folder: "/pages/images/uploads"

collections:
  - name: "Pages"
    label: "Pages"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "Posts"
    label: "Posts"
    folder: "docs/blog"
    create: true
    slug: "blog/{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}